xldeploy:
  extends:
    file: ../../docker-compose.yml
    service: xldeploy
  cpu_shares: 5

xlrelease:
  extends:
    file: ../../docker-compose.yml
    service: xlrelease
  cpu_shares: 5
  volumes:
    - ../../../../xlrelease/xlr-lm-ted-plugin/src/main/resources:/opt/xl-release-4.7.2-server/ext:rw
    - ./conf/script.policy:/opt/xl-release-4.7.2-server/conf/script.policy:rw


tedmock:
  image: deardooley/getsandbox
  volumes:
    - ./sandbox_input:/sandbox
  ports:
    - "8080:8080"
